In [1]:
animal = "elephant"

animal_big = animal.upper()
print(animal)
print(animal_big)

elephant
ELEPHANT


In [3]:
print(animal.count("e"))

2


In [4]:
fruit ="banana"
color = "yellow"

print("{}는 {}입니다.".format(fruit,color))


banana는 yellow입니다.


In [5]:
n=[3,6,8,6,3,2,4,6]
print(n.index(2))
print(n.count(6))

5
3


In [7]:
list=[4,3,1,2]
list.sort()
print(list)
list.reverse()
print(list)

list[:]=["가","나","다","라"]
list.reverse()
print(list)



[1, 2, 3, 4]
[4, 3, 2, 1]
['라', '다', '나', '가']


In [8]:
def sing():
    print("노래를 부릅니다. 카서스가 노래하네요. 다죽어라.")
sing()

노래를 부릅니다. 카서스가 노래하네요. 다죽어라.


In [9]:
sing()

노래를 부릅니다. 카서스가 노래하네요. 다죽어라.


In [10]:
def introduce(name):
    print(name+"입니다.")
introduce("홍길동")

홍길동입니다.


In [12]:
introduce("아무개")

아무개입니다.


In [1]:
import time
now_time = time.time()
print(now_time)

1655799424.304115


In [2]:
from time import time
now_time = time()
print(now_time)

1655799493.0667098


In [3]:
vage="potato"
print(len(vage))



6


In [8]:
number=[1,5,3,4,2]
number.sort()
print(number)
number=[1,5,3,4,2]
print(sorted(number))
print(number)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 5, 3, 4, 2]


In [2]:
def introduce(first="김", second="길동"):
    return "성은" + first+"이고, 이름은 "+second+"입니다."

print(introduce("홍"))

성은홍이고, 이름은 길동입니다.


In [4]:
def bmi(height,weight):
    return weight / height**2

print(bmi(1.65,65))

23.875114784205696


In [5]:
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [6]:
np.arange(4)

array([0, 1, 2, 3])

In [8]:
storages = [1,2,3,4]
new_storages= []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [14]:
#import numpy as np
storages = np.array([1,2,3,4])
storages += storages
print(storages)

[2 4 6 8]


In [16]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


In [21]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = arr1
arr2[0] = 100

print(arr1)

arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

print(arr1)


[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [26]:
arr3 = np.array([2, 4, 6, 7])
print(arr3[np.array([True,True,True,False])])

[2 4 6]


In [30]:
arr = np.array([2,4,6,7])
print(arr[arr%3 == 1])

[4 7]


In [32]:
arr = np.array([4,-9,16,-4,20])
print(arr)

arr_abs=np.abs(arr)
print(arr_abs)

print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [36]:
arr = np.array([2,2,4,5,6,2,4,6])

arr1 = np.unique(arr)
print(arr1)



[2 4 5 6]
[2 4 5 6]


In [39]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print(arr.shape)

print(arr.reshape(4, 2))




[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1])

print(arr[1,1:])

print(arr[1,2])

[4 5 6]
[5 6]
6


In [44]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [50]:
arr = np.arange(10).reshape(2,5)

print(arr.T)


[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [54]:
arr = np.array([[8,4,2],[3,5,1]])
print(arr.argsort())

print(np.sort(arr))

arr.sort(1)
print(arr)
    

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]
