#### 1. Scikit-learn modeling (5-steps)

In [1]:
from sklearn import datasets, model_selection, metrics, svm

iris = datasets.load_iris()
train_x, test_x, train_y, test_y = model_selection.train_test_split(iris.data, iris.target, test_size=0.3, random_state=0)

model = svm.SVC(C=1.0, gamma='auto')
model.fit(train_x, train_y)

predicted_y = model.predict(test_x)
print(metrics.accuracy_score(predicted_y, test_y))

0.9777777777777777


#### 2. Saving the trained model 

In [3]:
import joblib

joblib.dump(model, 'model_iris_svm_v1.pkl', compress=True)

['model_iris_svm_v1.pkl']

#### 3. Loading the trained model 

In [4]:
import joblib

model_loaded = joblib.load('model_iris_svm_v1.pkl')

print(metrics.accuracy_score(model_loaded.predict(test_x), test_y))

0.9777777777777777


In [5]:
test_x[0]

array([5.8, 2.8, 5.1, 2.4])

In [6]:
import numpy as np

sample_one = np.reshape(test_x[0], (1, 4))
sample_one

array([[5.8, 2.8, 5.1, 2.4]])

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
result = model_loaded.predict(sample_one)
result[0] # predicted class

2

In [9]:
iris.target_names # 2 == virginica 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris.target_names[result[0]]

'virginica'

In [11]:
test_y

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [12]:
test_x

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2