## 넘파이:ML 주요 알고리즘 -선형대수와 통계에 기반
* Numpy는  Numerical Python을 의미하며 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표 패키지
* 루프를 사용치 않고 대량 데이터의 배열 연산이 가능
* C/C++과 같은 저수준 언어 기반의 호환 API제공

In [4]:
# 라이브러리 호출
import numpy as np

In [7]:
l1 = [1, 2, 3]
# array 생성
array_l1 = np.array(l1)

# type과 shape을 확인한다.
print('array_l1 type : ', type(array_l1))
print('array_l1 shape : ', array_l1.shape) # property - shape, ndim

array_l1 type :  <class 'numpy.ndarray'>
array_l1 shape :  (3,)


In [12]:
# 차원 복습 - 2차원 생성
l2 = [[11, 22, 33],
     [44, 55, 66]] # 할당(Assignment), 선언(Declare)
array_l2 = np.array(l2)

print('array_l2 type : ', type(array_l2))
print('array_l2 shape : ', array_l2.shape) # property - shape, ndim

array_l2 type :  <class 'numpy.ndarray'>
array_l2 shape :  (2, 3)


In [14]:
# 차원 복습 - 3차원 생성
l3 = [[[11, 22, 33 ], [1, 2, 3]]]

array_l3 = np.array(l3)

print('array_l3 type : ', type(array_l3))
print('array_l3 shape : ', array_l3.shape) # property - shape, ndim


array_l3 type :  <class 'numpy.ndarray'>
array_l3 shape :  (1, 2, 3)


# ndarray를 편리하게 생성

## arange 활용

In [17]:
sq_array = np.arange(10) # n-1까지 n개 생성
sq_array
# start 파라미터, stop 파라미터 활용
sq_array2 = np.arange(3, 10)
sq_array2

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
print(sq_array.dtype, sq_array.shape)
sq_array

int32 (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## zeros 활용

In [22]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array.dtype, zero_array.shape)
zero_array

int32 (3, 2)


array([[0, 0],
       [0, 0],
       [0, 0]])

## ones 활용

In [24]:
ones_array = np.ones((1, 3, 2), dtype='int32')
print(ones_array.dtype, ones_array.shape)
ones_array

int32 (1, 3, 2)


array([[[1, 1],
        [1, 1],
        [1, 1]]])

# reshape을 활용한 차원호환

In [38]:
# 1차원
sqr_array = np.arange(1, 11)
# 2차원
sqr_array.reshape(2, 5)
sqr_array.reshape(-1, 1)
sqr_array.reshape(5, -1)
# 3차원
sqr_array3 = np.arange(1, 9)
sqr_array3
sqr_array3d = sqr_array3.reshape(2,2,2)

In [42]:
# sqr_array3d -> sql_array1d
sqr_array1d = sqr_array3d.reshape(-1)
# sqr_array3d -> sql_array2d
sqr_array2d = sqr_array3d.reshape(2, 4)

In [ ]:
# end of file