### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택 할 수 있도록 하는 인덱싱에 대한 알아보자
#### 1.특정한 데이터만 추출
#### 2.슬라이싱(Slicing)
#### 3.팬시 인덱싱(Fancy Indexing)
#### 4.불린 인덱싱(Boolean Indexing)

In [10]:
import numpy as np
# 1-9까지 1차원 ndarray생성
array1 = np.arange(1, 10, dtype='int32')
value = array1[-1]
print('value : ', value)
print('type : ', type(value))

value :  9
type :  <class 'numpy.int32'>


In [16]:
array1d = array1.copy()
array2d = array1d.reshape(-1, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print('(row =0, col=0) index 가리키는 값 : ', array2d[0, 0])
print('(row =0, col=0) index 가리키는 값 : ', array2d[0][0])
print('(row =0, col=1) index 가리키는 값 : ', array2d[0, 1])
print('(row =0, col=2) index 가리키는 값 : ', array2d[0, 2])
print('(row =1, col=0) index 가리키는 값 : ', array2d[1, 0])
print('(row =2, col=2) index 가리키는 값 : ', array2d[2, 2])

(row =0, col=0) index 가리키는 값 :  1
(row =0, col=0) index 가리키는 값 :  1
(row =0, col=1) index 가리키는 값 :  2
(row =0, col=2) index 가리키는 값 :  3
(row =1, col=0) index 가리키는 값 :  4
(row =2, col=2) index 가리키는 값 :  9


## 2. 슬라이싱(Slicing) - 2차원

In [44]:
print(array2d)
print('array2d(0:2, 0:2):\n', array2d[0:2, 0:2])
print('array2d(1:3, 0:3):\n', array2d[1:3, 0:3])
print('array2d(1:, :):\n', array2d[1:, :])

## question 1
print('array2d(:2, 0):\n', array2d[:2, 0])
print('array2d(:2, 0:1):\n', array2d[:2, 0:1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d(0:2, 0:2):
 [[1 2]
 [4 5]]
array2d(1:3, 0:3):
 [[4 5 6]
 [7 8 9]]
array2d(1:, :):
 [[4 5 6]
 [7 8 9]]
array2d(:2, 0):
 [1 4]
array2d(:2, 0:1):
 [[1]
 [4]]


## 3. 팬시 인덱싱(Fancy Indexing)

In [39]:
print(array2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(array2d[[0,1], 2])
print(array2d[[0,1], 2:])

[3 6]
[[3]
 [6]]


In [51]:
from sklearn.datasets import load_iris
import pandas as pd

In [56]:
iris_df = pd.DataFrame(load_iris().data)
iris_df.rename(columns={0:'a',
               1:'b',
               2:'c',
               3:'d'}, inplace=True)

In [63]:
type(iris_df)

pandas.core.frame.DataFrame

In [64]:
type(iris_df[['a']])

pandas.core.frame.DataFrame