In [ ]:
%%timeit
x = 5
y = 7
if x > 5:
    x += 1
    y = 8

In [ ]:
%matplotlib

In [ ]:
# getattr('a a b s' ,'split')
# hasattr('abd ', 'sum')

In [ ]:
iter('test')

def isiterable(obj):
    try:
        iter(obj)
        return True
    except:
        return False

x = 123

if not isinstance(x, list) and isiterable(x):
    x = list(x)




In [ ]:
a = [1, 2, 3]

b = list(a)

c = a


a is b
# a == b

In [ ]:
test = 'a\n\a\b'
test_r = r'a\n\a\b'


test

test_r

In [ ]:
template = '{0:.2f} {1:s} test {2:d}'
template.format(4.556, 'Argentine Persos', 1)

In [ ]:
val = 'espanol'
b = val.encode('utf-8')

# b.decode('utf-8')



In [ ]:
# import pandas as pd

# video_df = pd.read_csv('../../coper-project/data/침착맨_videos.csv', encoding='utf-8' , engine='python')

my_name = 'my name is tester'
tup_name = tuple(my_name)


t = [[1, 2, 3]]


tuple_test = tuple(t) * 4


# tuple_test[0] is tuple_test[1]

# tuple_test[0] is tuple_test[2]

# tuple_test[0] is tuple_test[3]

tuple_test[0].append(4)

tuple_test

In [ ]:
key = 1, 2, 3, 4
value = 'a', 'b', 'c', 'd'

{k : v for k, v in zip(key, value)}



value = 1, 2, [3, 4]
key = 'a', 'b', 'c', 'd'

test = {k : v for k, v in zip(key, value)}


In [ ]:
pitchars = [('Nolan', 'Pyan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')]

first_name, list_name = zip(*pitchars)


In [ ]:
from collections import defaultdict

words = ['apple', 'bat', 'bar', 'atom', 'book']

by_letter = defaultdict(list)

for word in words:
    by_letter[word[0]].append(word)
by_letter

In [ ]:
tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

a = [x for tup in tuples for x in tup]

dicts = [{'1' : 1, '2' : 2, '3' : 3}, {'5' : 6, '고양이' : '야옹'}, {'강아지' : '멍멍'}]


test = {k : v for value in dicts for k, v in value.items()}



numbers = [['1', '2', '4'], ['5', '6', '8'], ['3', '9', '0', '4']]


x = [x for number in numbers for x in number]

x

In [ ]:
tup = (1, 2, 3, 5, 6, 7, 8)
*x, y, z = tup
# result x : [1, 2, 3, 4, 5, 6], y : 7, z : 8
print(f'x : {x}, y : {y}, z : {z}')

In [ ]:
import re
def remove_punctuation(value):
    return re.sub('[!?#@^0-9]', '', value)

ops = [str.strip, str.title, remove_punctuation]


def clean_text(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result


text = ['qweasda', 'ewqewqe#!', 'ewqeqe0ldasd', '3eee2adas89', '4#!@adasdasd']
clean_text(text, ops)

In [5]:
def add_numbers(x, y):
    return x + y

# add_five = lambda y : add_numbers(5, y)

# for i in range(1, 6):
#     number = add_five(i)
#     print(number)
    
from functools import partial
add_five = partial(add_numbers, 5)

# for i in range(1, 6):
#     number = add_five(i)
#     print(number)

add_five(2)

7

In [ ]:
some_dict = {'a' : 1, 'b' : 2, 'c' : 23}

dict_iterator = iter(some_dict)

list(dict_iterator)

def squares(n=10):
    print('Generating squares from 1 to {0}.'.format(n ** 2))
    for i in range(1, n+1):
        yield i ** 2
        
gen = squares()

    
my_list = [i for i in gen]
my_list

In [ ]:
gen = (i ** 2 for i in range(5))

for i in gen:
    print(i)

In [ ]:
new_gen = (i ** 2 for i in range(10))

sum(x ** 2 for i in range(10))

In [ ]:
import itertools

first_text = lambda x : x[0]

names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']

# for text, names in itertools.groupby(names, first_text):
#     print(text, list(names))

# 6가지
numbers = [1, 2, 3, 4]

# 3가지
numbers = [1, 2, 3]
for text, numbers in itertools.combinations(numbers, 2):
    print(text, numbers)

In [81]:
def mul(m):
    def test(self, a):
        return a * 2
    
    def wrapper(n):
        return m * n
    return wrapper

   
        
mul3 = mul(3)
mul5 = mul(5)

print(mul3(10))
print(mul5(10))

30
50


AttributeError: 'function' object has no attribute 'test'

In [58]:
def test(m):
    def a(n:iter):
        lists = [i for i in n if i%2==0]
        return lists
    return a


test1 = test(2)
test2 = test(3)

test1([1, 2, 3, 4, 5, 6, 7])
test2([2, 3, 4, 5, 6, 7])




[2, 4, 6]

In [65]:
import numpy as np

my_arr = np.arange(1000000)

%time for _ in range(10): my_arr = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 13 ms


In [64]:
my_list = list(range(1000000))

%time for _ in range(10) : my_list = my_list * 2

CPU times: total: 14.2 s
Wall time: 14.2 s


In [67]:
data = np.random.randn(2, 3)
data * 10

data + data

array([[-0.47264584, -1.50921392, -2.51945264],
       [ 0.94167666, -1.19038988,  0.68814999]])

In [70]:
empty_unit32 = np.empty(8, dtype='u4')

# empty_unit32



array([   4128860,    6029375,    3801155,    5570652,    6619251,
          7536754, 4294901760, 4294967295], dtype=uint32)

In [71]:
import tensorflow

tensorflow.__version__

'2.10.0'

## 브로드캐스팅

In [16]:
import numpy as np
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
# 뷰 : 원본배열에 그대로 반영
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])