In [2]:
import numpy as np
import pandas as pd

In [ ]:
%%timeit
x = 5
y = 7
if x > 5:
    x += 1
    y = 8


In [ ]:
%matplotlib

In [ ]:
# getattr('a a b s' ,'split')
# hasattr('abd ', 'sum')

In [ ]:
iter('test')

def isiterable(obj):
    try:
        iter(obj)
        return True
    except:
        return False

x = 123

if not isinstance(x, list) and isiterable(x):
    x = list(x)




In [ ]:
a = [1, 2, 3]

b = list(a)

c = a


a is b
# a == b

In [ ]:
test = 'a\n\a\b'
test_r = r'a\n\a\b'


test

test_r

In [ ]:
template = '{0:.2f} {1:s} test {2:d}'
template.format(4.556, 'Argentine Persos', 1)

In [ ]:
val = 'espanol'
b = val.encode('utf-8')

# b.decode('utf-8')



In [ ]:
# import pandas as pd

# video_df = pd.read_csv('../../coper-project/data/침착맨_videos.csv', encoding='utf-8' , engine='python')

my_name = 'my name is tester'
tup_name = tuple(my_name)


t = [[1, 2, 3]]


tuple_test = tuple(t) * 4


# tuple_test[0] is tuple_test[1]

# tuple_test[0] is tuple_test[2]

# tuple_test[0] is tuple_test[3]

tuple_test[0].append(4)

tuple_test

In [ ]:
key = 1, 2, 3, 4
value = 'a', 'b', 'c', 'd'

{k : v for k, v in zip(key, value)}



value = 1, 2, [3, 4]
key = 'a', 'b', 'c', 'd'

test = {k : v for k, v in zip(key, value)}


In [ ]:
pitchars = [('Nolan', 'Pyan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')]

first_name, list_name = zip(*pitchars)


In [ ]:
from collections import defaultdict

words = ['apple', 'bat', 'bar', 'atom', 'book']

by_letter = defaultdict(list)

for word in words:
    by_letter[word[0]].append(word)
by_letter

In [ ]:
tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

a = [x for tup in tuples for x in tup]

dicts = [{'1' : 1, '2' : 2, '3' : 3}, {'5' : 6, '고양이' : '야옹'}, {'강아지' : '멍멍'}]


test = {k : v for value in dicts for k, v in value.items()}



numbers = [['1', '2', '4'], ['5', '6', '8'], ['3', '9', '0', '4']]


x = [x for number in numbers for x in number]

x

In [ ]:
tup = (1, 2, 3, 5, 6, 7, 8)
*x, y, z = tup
# result x : [1, 2, 3, 4, 5, 6], y : 7, z : 8
print(f'x : {x}, y : {y}, z : {z}')

In [ ]:
import re
def remove_punctuation(value):
    return re.sub('[!?#@^0-9]', '', value)

ops = [str.strip, str.title, remove_punctuation]


def clean_text(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result


text = ['qweasda', 'ewqewqe#!', 'ewqeqe0ldasd', '3eee2adas89', '4#!@adasdasd']
clean_text(text, ops)

In [5]:
def add_numbers(x, y):
    return x + y

# add_five = lambda y : add_numbers(5, y)

# for i in range(1, 6):
#     number = add_five(i)
#     print(number)
    
from functools import partial
add_five = partial(add_numbers, 5)

# for i in range(1, 6):
#     number = add_five(i)
#     print(number)

add_five(2)

7

In [ ]:
some_dict = {'a' : 1, 'b' : 2, 'c' : 23}

dict_iterator = iter(some_dict)

list(dict_iterator)

def squares(n=10):
    print('Generating squares from 1 to {0}.'.format(n ** 2))
    for i in range(1, n+1):
        yield i ** 2
        
gen = squares()

    
my_list = [i for i in gen]
my_list

In [ ]:
gen = (i ** 2 for i in range(5))

for i in gen:
    print(i)

In [ ]:
new_gen = (i ** 2 for i in range(10))

sum(x ** 2 for i in range(10))

In [ ]:
import itertools

first_text = lambda x : x[0]

names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']

# for text, names in itertools.groupby(names, first_text):
#     print(text, list(names))

# 6가지
numbers = [1, 2, 3, 4]

# 3가지
numbers = [1, 2, 3]
for text, numbers in itertools.combinations(numbers, 2):
    print(text, numbers)

In [81]:
def mul(m):
    def test(self, a):
        return a * 2
    
    def wrapper(n):
        return m * n
    return wrapper

   
        
mul3 = mul(3)
mul5 = mul(5)

print(mul3(10))
print(mul5(10))

30
50


AttributeError: 'function' object has no attribute 'test'

In [58]:
def test(m):
    def a(n:iter):
        lists = [i for i in n if i%2==0]
        return lists
    return a


test1 = test(2)
test2 = test(3)

test1([1, 2, 3, 4, 5, 6, 7])
test2([2, 3, 4, 5, 6, 7])




[2, 4, 6]

In [65]:
import numpy as np

my_arr = np.arange(1000000)

%time for _ in range(10): my_arr = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 13 ms


In [64]:
my_list = list(range(1000000))

%time for _ in range(10) : my_list = my_list * 2

CPU times: total: 14.2 s
Wall time: 14.2 s


In [67]:
data = np.random.randn(2, 3)
data * 10

data + data

array([[-0.47264584, -1.50921392, -2.51945264],
       [ 0.94167666, -1.19038988,  0.68814999]])

In [70]:
empty_unit32 = np.empty(8, dtype='u4')

# empty_unit32



array([   4128860,    6029375,    3801155,    5570652,    6619251,
          7536754, 4294901760, 4294967295], dtype=uint32)

In [71]:
import tensorflow

tensorflow.__version__

'2.10.0'

## 브로드캐스팅

In [1]:
import numpy as np
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
# 뷰 : 원본배열에 그대로 반영
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [39]:
arr = [[_ for _ in range(1, 4)], [_ for _ in range(4, 7)], [_ for _ in range(7, 10)]]


In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


'''
    0  1  2
0 [[1, 2, 3]
1 [4, 5, 6]
2 [7, 8, 9]]

[n : m-1, n : m-1]
'''

arr[:1, :2]
arr[:2, :1]



array([[1],
       [4]])

In [124]:
names = np.array(['Bob', 'Joe', 'Minho', 'Juyoung', 'TeaYoung', 'Bob', 'Bob', 'Minho'])

random_data = np.random.randn(len(names), 4)
random_data

# names를 벡터화시켜 Bob에 맞는 데이터들을 가져온다.
random_data[names == 'Bob']


array([[-0.69715769,  0.54772226,  0.7922781 ,  0.83140311],
       [ 0.70170807, -0.11929893, -0.13396727, -0.40545753],
       [ 1.33511197, -0.15734128,  0.6806282 ,  1.38417413]])

In [139]:
poins = np.arange(-5, 5, 0.01)

xarr = np.array(np.arange(1.1, 1.6, 0.1))
yarr = np.array(np.arange(2.1, 2.6, 0.1))

cond = [False, True, False, True, False]
cond

result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

# 2.1, 1.1, 
np.where(cond, xarr, yarr)
# result

array([2.1, 1.2, 2.3, 1.4, 2.5])

In [2]:
import numpy as np
arr = np.arange(32).reshape(8, 4)
print(arr)
print('-------------------------------')
# (1, 0), (5, 3), (7, 1), (2, 2)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print('-------------------------------')
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------------------------------
[ 4 23 29 10]
-------------------------------
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [4]:
arr = np.arange(15).reshape(-1, 5)
print(arr)
print('------------------')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [3]:
import pandas as pd
x = np.array([[1., 2.1, 3.], [4.1, 5.1, 6.]])
y = np.array([[6., 23.], [-1, 7.], [8, 9]])
# 행렬곱 = 벡터 내적곱
np.dot(x, y)


array([[ 27.9,  64.7],
       [ 67.5, 184. ]])

In [4]:
obj = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])
obj[obj > 0]

a    4
b    7
d    3
dtype: int64

In [5]:
np.exp(obj)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [22]:
df = pd.DataFrame(np.arange(10).reshape(-1, 2), index=np.arange(2000, 2005), columns=['Nevada', 'Ohio'])

df

Nevada  Ohio
2000       0     1
2001       2     3
2002       4     5
2003       6     7
2004       8     9

In [35]:
data = pd.DataFrame(np.arange(16).reshape(-1, 4), index=['Ohio', 'Colorabo', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
print(data)
# data.loc['Colorabo', ['two', 'three']]
# data.iloc[1:2, 1:3]
data.iloc[1:2, [1, 2]]

          one  two  three  four
Ohio        0    1      2     3
Colorabo    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


two  three
Colorabo    5      6

In [40]:
# data.loc[:'Utah', 'one':'three']

arr = np.arange(30).reshape(-1, 5)
arr[::2, ::-1]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [48]:
index_list = []
for i in range(65, 65+11):
    index_list.append(chr(i))

columns_list = []

df = pd.DataFrame(np.arange(1.1, 9.9, 0.2).reshape(-1, 4), index=index_list)
df

# 44032, 45208, 45796, 46972
test = ord('라')



46972