In [1]:
import numpy as np # alias (별칭)

# 차원의 사례

In [37]:
a = [1, 2, 3]
b = np.array(a)

In [38]:
# a는 일반 list 이다.
# b는 ndarray 이다.

print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
array1 = b.copy()
array2 = np.array([4, 5, 6])
print('array1 type:', type(array1))
print(array1) # (1, 3) 한 요소를 추출하는데 필요한 최소 첨자수가 한 개이므로...
print('array1의 형태 : ', array1.shape)
# print(array2)

array1 type: <class 'numpy.ndarray'>
[1 2 3]
array1의 형태 :  (3,)


In [42]:
# 2차원 자료 생성해보기
array2d = np.array([[1, 2, 3], [11, 22, 33]]) # (2 ,3)
print('array2d type:', type(array2))
print('array2d의 형태 : ', array2d.shape)

array2d type: <class 'numpy.ndarray'>
array2d의 형태 :  (2, 3)


In [44]:
array3d = [[[1, 2]]]
print('array2d의 형태 : ', array2d.shape)

array2d의 형태 :  (2, 3)


In [27]:
# 3차원의 자료 생성해보기
array3d = np.array([[[1, 2, 3], [11, 22, 33]]]) # (1, 2, 3) -> (1, 1, 3)

print('array3d type : ', type(array3d))
print('array3d의 형태 : ', array3d.shape)
print(f'array3d는 {array3d.ndim}차원')

array3d type :  <class 'numpy.ndarray'>
array3d의 형태 :  (1, 2, 3)
array3d는 3차원


In [33]:
# 3차원의 자료 생성해보기
array3d = np.array([[[11, 22, 33]]]) # (1, 1, 3) / (2, 1, 3) / 

print('array3d의 형태 : ', array3d.shape)
print(f'array3d는 {array3d.ndim}차원')

array3d = np.array([[[11, 22, 33]], [[1, 2, 3]]]) # (1, 1, 3) / (2, 1, 3) / 

print('array3d의 형태 : ', array3d.shape)
print(f'array3d는 {array3d.ndim}차원')


array3d의 형태 :  (1, 1, 3)
array3d는 3차원
array3d의 형태 :  (2, 1, 3)
array3d는 3차원


In [14]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In [16]:
array_x = np.array(x)
array_y = np.array(y)
list(array_x + array_y)

[5, 7, 9]

In [60]:
# 또 다른 용례
# 결측값 = 빈 값
array_test = np.array([[1, 2, 3], [11, 22, 33, 44]])
print('array_test의 형태 : ', array_test.shape)
print(f'array_test는 {array_test.ndim}차원')


array_test의 형태 :  (2,)
array_test는 1차원


C:\Users\TECH2_07\AppData\Local\Temp\ipykernel_6220\1502945812.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_test = np.array([[1, 2, 3], [11, 22, 33, 44]])


# ndarray 편리하게 생성 - arange, zeros, ones

In [83]:
# arange
# np.arange(start=1, stop=11)
seq_array = np.arange(1, 11)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
int32 (10,)


In [90]:
# zeros로 0으로 된 행렬을 생성
zero_array = np.zeros((2, 4), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0 0 0]
 [0 0 0 0]]
int32 (2, 4)


In [4]:
import numpy as np
array1ds = np.arange(1, 11)
# [1, 2, 3, 4, ..., 10]
array1ds.reshape(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [92]:
# ones로 1으로 된 행렬을 생성
ones_array = np.ones((3, 2), dtype='int32')
print(ones_array)
print(ones_array.dtype, ones_array.shape)


array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

> CPU라는 것... python, R은 그냥 내 컴퓨터의 사양 최대치....

# reshape의 용례

In [81]:
seq_array.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
%autosave 50

# numpy의 dtype

In [101]:
# Numpy의 데이터 타입은 다 같은 타입으로 구성된다.
l2 = [1, 2, 'test']

# ap.array를 활용하여 ndarray로 변환
array2 = np.array(l2)

l3 = [1, 2, 5.5]
array3 = np.array(l3)
print(array3, array3.dtype)


[1.  2.  5.5] float64


# dtype의 상호 변환

In [5]:
# dtype의 상호 변환 - astype
array_int = np.array([1, 3, 5])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# array_float => array_int2
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

# 자료에 따른 버림현상
array_float2 = np.array([1.1, 2.2, 3.3, 4.9])
array = array_float2.astype('int32')


[1. 3. 5.] float64
[1 3 5] int32


array([1., 3., 5.])

In [9]:
array_int = np.array([1, 3, 5])
# int => float으로 형변환
array_float = array_int.astype('float64')
# [1., 3. 5.], dtype ==> float64
print(f'array_float : {array_float}, dtype ==> {array_float.dtype}')

array_float : [1. 3. 5.], dtype ==> float64
