# 행렬의 정렬 - sort(), argsort()

In [15]:
import numpy as np
org_arr = np.array([3, 1, 9, 5])

sort_arr = np.sort(org_array)
# np.sort()로 정렬 - 원본 불변
print(f'org_arr : {org_arr} / sort_arr : {sort_arr}')

# ndarray.sort()로 정렬 - 원본 변함
sort_arr = org_array.sort()
print(f'org_arr : {org_array} / sort_arr : {sort_arr}')



org_arr : [3 1 9 5] / sort_arr : [1 3 5 9]
org_arr : [1 3 5 9] / sort_arr : None


In [19]:
# 내림차순
desc_arr = np.sort(org_arr)[::-1]
print(f'org_arr : {org_arr} / desc_arr : {desc_arr}')

org_arr : [3 1 9 5] / desc_arr : [9 5 3 1]


In [25]:
# axis에 따른 정렬...
array2d = np.array([[4,12], [7, 1],])

sort_array2d_ax0 = np.sort(array2d, axis=0)
print(f'로우(행) 방향으로 위아래 정렬 [axis=0] : \n {sort_array2d_ax0}')
sort_array2d_ax1 = np.sort(array2d, axis=1)
print(f'컬럼(열) 방향으로 좌우 정렬 [axis=1] : \n {sort_array2d_ax1}')

로우(행) 방향으로 정렬 [axis=0] : 
 [[ 4  1]
 [ 7 12]]
컬럼(열) 방향으로 정렬 [axis=1] : 
 [[ 4 12]
 [ 1  7]]


* argsort()함수 : 정렬된 행렬의 인덱스 변환!!!

In [27]:
org_arr = np.array([3, 1, 9, 5,])  # sort => 1, 3, 5, 9
                  # 0  1  2  3     # 1, 0, 3, 2
sort_arr = np.argsort(org_arr)
print(f'행렬 정렬 후 원본행렬의 인덱스 : {sort_arr}')

행렬 정렬 후 원본행렬의 인덱스 : [1 0 3 2]


# 행렬의 내적 (:: 행렬곱)

In [28]:
# 2, 3
A = np.array([[1, 2, 3], [3, 4, 5]])

# 3, 2
B = np.array([[7, 8], [9, 10], [11, 12]])
np.dot(A, B)

array([[ 58,  64],
       [112, 124]])

# 전치행렬(Transpose)

In [30]:
A = np.array([[1, 2], [3, 4]])

transpose_A = np.transpose(A)
transpose_A

B = np.array([[1, 2], [3, 4], [5, 6]])
transpose_B = np.transpose(B)
transpose_B


array([[1, 3, 5],
       [2, 4, 6]])

# Pandas - index

In [2]:

import pandas as pd
# Name, Year, Gender

data = {
        'Name' : ['Chulmin', 'Eunkyoung', 'Jiwoong', 'Soobeom'],
        'Year' : [2011, 2016, 2015, 2015],
        'Gender' : ['Male', 'Female', 'Male', ' Male'],
}

data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [15]:
# 인덱싱 시작 1 - 컬럼명
# data_df[['Name']]
data_df['Name']

one        Chulmin
two      Eunkyoung
three      Jiwoong
four       Soobeom
Name: Name, dtype: object

In [18]:
# 인덱싱 시작 1 - 행은 슬라이싱으로만 !!
data_df[0:3]

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [26]:
# 단일값 불러오기1 - loc(lable::명칭) // iloc(Positional - 위치)
data_df.loc['three', 'Name'] # loc

'Jiwoong'

In [27]:
data_df.iloc[2, 0] # iloc

'Jiwoong'

In [28]:
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [57]:
# 연습
data_df.iloc[0:2, 0:2]
data_df.iloc[0:2, [0,1]]
# data_df.iloc[0:2, (0,1)]
data_df.loc['one' : 'two', 'Name' : 'Year']

data_df.loc[data_df['Year']>2014][:2]

Name  Year
one    Chulmin  2011
two  Eunkyoung  2016

In [61]:
## 타이타닉 데이터의 index의 특징
titan_df = pd.read_csv('./titanic/train.csv')
## Index 객체 추출
Indexes = titan_df.index
## Index 객체를 실제 값 array로 변환
print('Index 객체 array:\n', Indexes.values[:5])

Index 객체 array:
 [0 1 2 3 4]


In [63]:
print(type(Indexes.values))
print(Indexes.values.shape)

<class 'numpy.ndarray'>
(891,)


In [66]:
# 단 번에 인덱스 값을 바꿀 수는 없습니다.
# Indexes[0] = 1000
# 인덱스 값을 바꾸고 싶으시다면, Index.values를 하고
# 변화한 값을 다시금 pd.DataFrame(Index=Index.values)이렇게 바꾸셔야 합니다.